services:
  php:
    image: 'wodby/php:8.1'
    ports:
      - 80:80
    command: 'php -S 0.0.0.0:80 -t ./public'
    working_dir: '/var/www/html'
    volumes:
      - '.:/var/www/html'
    environment:
      - PHP_XDEBUG=1
      - PHP_XDEBUG_MODE=debug
      - PHP_XDEBUG_CLIENT_HOST=host.docker.internal
      - PHP_XDEBUG_IDEKEY="vscode"
      - PHP_XDEBUG_START_WITH_REQUEST="yes"
      - PHP_XDEBUG_LOG_LEVEL=0
      - PHP_IDE_CONFIG="serverName=php"